-- ============================================================================
-- Migration 020: داشبورد المدير/الإدمن — مراجعة المحادثات + عدّاد الحالات
--                + نظرة عامة على الاشتراكات
-- ============================================================================
-- الهدف: واجهة داخلية جديدة (تطبيق ويب منفصل) لمدير المشروع بس (مش الأطباء)،
-- عشان:
--   1) يراجع كل محادثة دكتور↔AI سطر بسطر، ولكل رد للـ AI يوصل مباشرة للـ
--      execution بتاعه في n8n (شاف عمل إيه بالظبط ولمس إيه في الداتا).
--   2) يشوف عدد الحالات لكل دكتور شهريًا (مدخل الحساب اليدوي للفلوس).
--   3) يشوف كل مساحة عمل مشتركة في إيه (باقة) وبتستخدم فعليًا إيه من
--      البوتات التلاتة (clinic/round/ed) مقارنة بالمُتاح ليها في باقتها.
--
-- الدخول على كل حاجة هنا (app_admins + admin_*) بيتطلب Supabase Auth
-- (authenticated) + وجود صف في app_admins — منفصل تمامًا عن آلية هوية
-- الأطباء (platform/bot_key/chat_id) اللي البوتات بتستخدمها.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1) سجل تنفيذات الفلو — الحلقة الناقصة بين n8n_chat_histories وبين n8n نفسه
-- ----------------------------------------------------------------------------
-- كل توّرن (turn) ناجح من الـ AI Agent بيسجّل هنا صف واحد بمعرّف التنفيذ
-- (execution) بتاعه في n8n. بيتسجّل من نفس الـ workflow، بعد ما الأجنت يرد
-- وقبل الرد للطبيب — لو الإدراج فشل الرد للطبيب لازم يكمل عادي (onError على
-- مستوى العقدة في n8n، مش هنا).

create table if not exists public.flow_execution_log (
  id               bigint generated by default as identity,
  workspace_id     uuid,
  org_id           uuid,
  staff_id         uuid,
  bot_key          text not null,
  chat_id          text not null,
  session_id       text not null,   -- نفس مفتاح n8n_chat_histories: chat_id || '-' || bot_key
  n8n_execution_id text not null,
  n8n_workflow_id  text not null,
  occurred_at      timestamptz not null default now(),
  constraint flow_execution_log_pkey primary key (id),
  constraint flow_execution_log_workspace_id_fkey foreign key (workspace_id) references public.workspaces(id),
  constraint flow_execution_log_org_id_fkey       foreign key (org_id)       references public.orgs(id),
  constraint flow_execution_log_staff_id_fkey      foreign key (staff_id)     references public.staff(id)
);

create index if not exists ix_flow_execution_log_session
  on public.flow_execution_log (session_id, occurred_at);

create index if not exists ix_flow_execution_log_workspace
  on public.flow_execution_log (workspace_id, occurred_at);

-- دالة التسجيل نفسها — بتتنادى من n8n بنفس أسلوب أي app_* تاني (add_orders،
-- prescribe، ...): بتاخد (platform, bot_key, chat_id) الخام وتعيد اشتقاق
-- الهوية عن طريق app_bind، مش بتاخد staff_id/workspace_id جاهزين من n8n.
create or replace function public.app_log_flow_execution(
  p_platform text, p_bot_key text, p_chat_id text,
  p_execution_id text, p_workflow_id text
)
returns void
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare
  c app_ctx;
begin
  c := app_bind(p_platform, p_bot_key, p_chat_id, false); -- بدون touch، الـ Resolve Staff في أول الفلو عمل ده أصلًا

  insert into flow_execution_log
    (workspace_id, org_id, staff_id, bot_key, chat_id, session_id, n8n_execution_id, n8n_workflow_id)
  values
    (c.workspace_id, c.org_id, c.staff_id, p_bot_key, p_chat_id,
     p_chat_id || '-' || p_bot_key, p_execution_id, p_workflow_id);
end;
$$;

grant execute on function public.app_log_flow_execution(text, text, text, text, text) to anon;

-- ----------------------------------------------------------------------------
-- 2) هوية المدير — allow-list منفصلة عن جدول staff (اللي هو للأطباء)
-- ----------------------------------------------------------------------------

create table if not exists public.app_admins (
  id         uuid not null references auth.users(id) on delete cascade,
  email      text not null,
  role       text not null default 'admin' check (role = any(array['owner','admin'])),
  created_at timestamptz not null default now(),
  constraint app_admins_pkey primary key (id)
);

alter table public.app_admins enable row level security;

drop policy if exists app_admins_self_select on public.app_admins;
create policy app_admins_self_select on public.app_admins
  for select using (id = auth.uid());

create or replace function public.app_is_admin()
returns boolean
language sql
stable
security definer
set search_path to 'public', 'pg_temp'
as $$
  select exists (select 1 from public.app_admins where id = auth.uid());
$$;

grant execute on function public.app_is_admin() to authenticated;

-- ملاحظة تشغيل: أول مدير بيتضاف يدويًا بعد أول تسجيل دخول على تطبيق
-- الداشبورد، بنفس روح إنشاء أول طبيب يدويًا:
--   insert into app_admins(id, email, role)
--   select id, email, 'owner' from auth.users where email = 'you@example.com';

-- ----------------------------------------------------------------------------
-- 3) admin_conversations_feed — محادثة دكتور معيّن + لينك تنفيذ كل رد AI
-- ----------------------------------------------------------------------------
-- بيدّي الأولوية لـ staff_id (مش session_id نصي) عشان الداشبورد بيختار
-- الدكتور من قايمة (dropdown)، فمفيش داعي نفكّك session_id يدويًا.

create or replace function public.admin_conversations_feed(
  p_staff_id uuid,
  p_bot_key  text default null,
  p_since    timestamptz default null,
  p_limit    integer default 200,
  p_offset   integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
begin
  if not app_is_admin() then
    raise exception 'AWN_FORBIDDEN: للإداريين فقط.';
  end if;

  return coalesce((
    select jsonb_agg(to_jsonb(page) order by page.msg_id desc)
    from (
      with channels as (
        select sc.bot_key, sc.external_id as chat_id,
               (sc.external_id || '-' || sc.bot_key) as session_id
          from staff_channels sc
         where sc.staff_id = p_staff_id
           and sc.is_active
           and (p_bot_key is null or sc.bot_key = p_bot_key)
      ),
      numbered as (
        select h.id as msg_id, c.bot_key, h.session_id, h.message,
               row_number() over (partition by h.session_id order by h.id) as seq
          from n8n_chat_histories h
          join channels c on c.session_id = h.session_id
      ),
      turns as (
        select msg_id, bot_key, session_id, message,
               ((seq + 1) / 2) as turn_no,
               case when seq % 2 = 1 then 'human' else 'ai' end as fallback_role
          from numbered
      ),
      logs as (
        select l.session_id, l.n8n_workflow_id, l.n8n_execution_id, l.occurred_at,
               row_number() over (partition by l.session_id order by l.occurred_at, l.id) as turn_no
          from flow_execution_log l
          join channels c on c.session_id = l.session_id
      )
      select t.msg_id, t.bot_key,
             coalesce(t.message->>'type', t.message->'data'->>'type', t.fallback_role) as role,
             coalesce(t.message->>'content', t.message->'data'->>'content') as content,
             lg.n8n_workflow_id, lg.n8n_execution_id, lg.occurred_at
        from turns t
        left join logs lg on lg.session_id = t.session_id and lg.turn_no = t.turn_no
       where p_since is null or lg.occurred_at is null or lg.occurred_at >= p_since
       order by t.msg_id desc
       limit p_limit offset p_offset
    ) page
  ), '[]'::jsonb);
end;
$$;

grant execute on function public.admin_conversations_feed(uuid, text, timestamptz, integer, integer) to authenticated;

-- ----------------------------------------------------------------------------
-- 4) admin_case_counts — عدد حالات كل دكتور (مدخل الحساب اليدوي بالحالة)
-- ----------------------------------------------------------------------------

create or replace function public.admin_case_counts(
  p_month date default date_trunc('month', now())::date
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare
  v_since timestamptz;
  v_until timestamptz;
begin
  if not app_is_admin() then
    raise exception 'AWN_FORBIDDEN: للإداريين فقط.';
  end if;

  v_since := date_trunc('month', p_month);
  v_until := v_since + interval '1 month';

  return coalesce((
    select jsonb_agg(to_jsonb(t) order by t.month_count desc, t.full_name)
    from (
      select s.id as staff_id, s.full_name, s.specialty, s.status,
             w.id as workspace_id, w.name as workspace_name,
             o.name as org_name,
             count(e.*) filter (where e.opened_at >= v_since and e.opened_at < v_until) as month_count,
             count(e.*) as total_count,
             max(e.opened_at) as last_case_at
        from staff s
        join workspaces w on w.id = s.workspace_id
        join orgs o       on o.id = s.org_id
        left join encounters e on e.attending_staff_id = s.id
       where s.role = 'doctor'
       group by s.id, s.full_name, s.specialty, s.status, w.id, w.name, o.name
    ) t
  ), '[]'::jsonb);
end;
$$;

grant execute on function public.admin_case_counts(date) to authenticated;

-- ----------------------------------------------------------------------------
-- 5) admin_workspaces_overview — مين مشترك في إيه، وبيستخدم فعليًا إيه
-- ----------------------------------------------------------------------------
-- entitled_modules  = المُتاح حسب الباقة (plan_features)
-- modules_with_channel = البوتات اللي فيها على الأقل قناة نشطة لطبيب
-- modules_used_30d  = البوتات اللي فعلًا اتسجّلها تنفيذ فلو (flow_execution_log)
--                     في آخر 30 يوم — أدق مؤشر استخدام حقيقي.

create or replace function public.admin_workspaces_overview()
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
begin
  if not app_is_admin() then
    raise exception 'AWN_FORBIDDEN: للإداريين فقط.';
  end if;

  return coalesce((
    select jsonb_agg(to_jsonb(t) order by t.org_name, t.workspace_name)
    from (
      select w.id as workspace_id, w.name as workspace_name,
             o.name as org_name, o.kind as org_kind,
             p.key as plan_key, p.name as plan_name,
             (select count(*) from staff s
                where s.workspace_id = w.id and s.role = 'doctor' and s.status = 'active'
             ) as active_doctors,
             (select coalesce(array_agg(distinct f.key), '{}')
                from plan_features pf join features f on f.key = pf.feature_key
               where pf.plan_id = w.plan_id
             ) as entitled_modules,
             (select coalesce(array_agg(distinct b.key), '{}')
                from staff_channels sc
                join staff s2 on s2.id = sc.staff_id
                join bots b   on b.key = sc.bot_key
               where s2.workspace_id = w.id and sc.is_active
             ) as modules_with_channel,
             (select coalesce(array_agg(distinct l.bot_key), '{}')
                from flow_execution_log l
               where l.workspace_id = w.id and l.occurred_at >= now() - interval '30 days'
             ) as modules_used_30d
        from workspaces w
        join orgs o      on o.id = w.org_id
        left join plans p on p.id = w.plan_id
    ) t
  ), '[]'::jsonb);
end;
$$;

grant execute on function public.admin_workspaces_overview() to authenticated;
