-- ============================================================================
-- Migration 044: نظام QA/Debugging شامل لاختبار الذكاء الاصطناعي
-- ============================================================================
-- توسيع لميزة "اختبار الذكاء الاصطناعي" (migration 043) بحيث كل تشغيلة اختبار
-- بقت لها هوية دايمة (test_run_id) وتاريخ محادثة كامل وملاحظات structured
-- محفوظة في قاعدة البيانات (مش بس في ذاكرة المتصفح)، عشان نقدر بعدين:
--   1) نربط كل رسالة من البوت الحقيقي بتنفيذ n8n الحقيقي اللي طلعها (execution_id
--      + workflow_id) — البنية التحتية دي (flow_execution_log + app_log_flow_execution)
--      موجودة وشغالة بالفعل من migration 020، والبوتات الحقيقية (ed/round/clinic
--      mobile) بتنادي عليها فعليًا من داخل n8n.
--   2) نحلل السبب الجذري لكل ملاحظة (Root Cause Analysis) بالاستعانة بدليل حقيقي
--      (نص رسالة الخطأ الثابت من n8n، تنفيذ n8n المرتبط لو موجود) مش تخمين.
--   3) نصدّر تقرير هندسي كامل (Markdown + JSON) جاهز نديه لـ Claude Code يصلح
--      بيه الـ workflow نفسه من غير ما نشرحله المشكلة يدويًا.
--
-- ملاحظة مهمة: Log Execution في الفلوز الحقيقية بيشتغل بس لما الـ AI Agent
-- ينجح (onError: continueErrorOutput بيوديك لفرع تاني مفيهوش تسجيل تنفيذ) —
-- يعني رسايل فشل الوكيل (نفس نص "I'm sorry, doctor — something went wrong on
-- my end...") مالهاش execution_id تسجيلي، وده متوقّع ومسجّل صراحة في الكود هنا،
-- مش حاجة بنخترعها أو بنحاول نلفّها.
--
-- بيصلّح كمان باج حقيقي موجود من قبل: admin_conversations_feed (020) كانت
-- بتربط الرسايل بتنفيذات n8n بترقيم من أول المحادثة، وده غلط لأي محادثة أقدم
-- من وقت ما بدأ التسجيل. النسخة هنا بترقّم من آخر رسالة للخلف (turn_from_end)
-- زي التصحيح الموجود في migrations/022_fix_conversation_execution_pairing.sql.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 0) Sequences لتوليد أكواد بشرية القراءة (TEST-2026-0815-0042 / FLAG-0004)
-- ----------------------------------------------------------------------------
create sequence if not exists public.qa_test_run_seq;
create sequence if not exists public.qa_flag_seq;

-- ----------------------------------------------------------------------------
-- 1) الجداول
-- ----------------------------------------------------------------------------
create table if not exists public.qa_test_runs (
  test_run_id         text primary key,
  bot_key              text not null,
  status               text not null default 'running',   -- running/passed/failed/stopped/error
  started_at           timestamptz not null default now(),
  ended_at             timestamptz,
  test_staff_id        uuid references public.staff(id),
  test_chat_id         text,
  workspace_id         uuid references public.workspaces(id),
  persona_prompt       text,
  max_turns            integer,
  total_turns          integer not null default 0,
  total_flags          integer not null default 0,
  critical_flags       integer not null default 0,
  major_flags          integer not null default 0,
  minor_flags          integer not null default 0,
  parent_test_run_id   text references public.qa_test_runs(test_run_id),
  n8n_workflow_id      text,
  created_by           text
);
alter table public.qa_test_runs enable row level security;

create table if not exists public.qa_test_messages (
  id                bigint generated by default as identity primary key,
  test_run_id       text not null references public.qa_test_runs(test_run_id) on delete cascade,
  turn_no           integer not null,
  role              text not null,   -- 'tester' | 'bot' | 'system'
  content           text not null,
  occurred_at       timestamptz not null default now(),
  n8n_execution_id  text,
  n8n_workflow_id   text,
  is_agent_error    boolean not null default false
);
alter table public.qa_test_messages enable row level security;
create index if not exists ix_qa_test_messages_run on public.qa_test_messages (test_run_id, turn_no);

create table if not exists public.qa_test_flags (
  flag_id            text primary key,
  test_run_id        text not null references public.qa_test_runs(test_run_id) on delete cascade,
  turn_no            integer,
  message_id         bigint references public.qa_test_messages(id),
  severity           text not null default 'unclassified',   -- critical/major/minor/unclassified
  category           text not null default 'unknown',
  scenario           text,
  expected_behavior  text,
  actual_behavior    text,
  confidence         numeric,
  raw_flag_text      text not null,     -- سبب [FLAG: ...] الخام من التستر — بيتسجل فورًا قبل أي تحليل
  status             text not null default 'open',   -- open/analyzed
  created_at         timestamptz not null default now()
);
alter table public.qa_test_flags enable row level security;
create index if not exists ix_qa_test_flags_run on public.qa_test_flags (test_run_id);

create table if not exists public.qa_root_cause_analyses (
  id                          bigint generated by default as identity primary key,
  flag_id                     text not null references public.qa_test_flags(flag_id) on delete cascade,
  first_divergence_stage      text,
  first_divergence_node       text,
  root_cause_category         text,
  root_cause_explanation      text,
  evidence                    jsonb,
  downstream_impact           text,
  recommended_investigation   text,
  recommended_fix             text,
  confidence                  numeric,
  raw_llm_response             jsonb,
  analyzed_at                 timestamptz not null default now()
);
alter table public.qa_root_cause_analyses enable row level security;
create index if not exists ix_qa_rca_flag on public.qa_root_cause_analyses (flag_id);

-- ----------------------------------------------------------------------------
-- 2) بدء تشغيلة اختبار جديدة (أو regression مرتبطة بتشغيلة قديمة)
-- ----------------------------------------------------------------------------
create or replace function public.admin_qa_start_test_run(
  p_bot_key            text,
  p_test_staff_id      uuid,
  p_test_chat_id       text,
  p_workspace_id       uuid,
  p_persona_prompt     text,
  p_max_turns          integer,
  p_parent_test_run_id text default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare
  v_id    text;
  v_email text := coalesce((auth.jwt() ->> 'email'), '');
begin
  if not app_is_admin() then
    raise exception 'AWN_FORBIDDEN: للإداريين فقط.';
  end if;
  if p_bot_key not in ('ed', 'round', 'clinic') then
    raise exception 'AWN_BAD_INPUT: بوت مش معروف: %', p_bot_key;
  end if;

  v_id := 'TEST-' || to_char(now(), 'YYYY-MMDD') || '-' || lpad(nextval('qa_test_run_seq')::text, 4, '0');

  insert into qa_test_runs
    (test_run_id, bot_key, status, test_staff_id, test_chat_id, workspace_id,
     persona_prompt, max_turns, parent_test_run_id, created_by)
  values
    (v_id, p_bot_key, 'running', p_test_staff_id, p_test_chat_id, p_workspace_id,
     p_persona_prompt, p_max_turns, p_parent_test_run_id, v_email);

  return jsonb_build_object('test_run_id', v_id);
end;
$$;
grant execute on function public.admin_qa_start_test_run(text, uuid, text, uuid, text, integer, text) to authenticated;

-- ----------------------------------------------------------------------------
-- 3) تسجيل رسالة/ملاحظة أول بأول أثناء الاختبار
-- ----------------------------------------------------------------------------
create or replace function public.admin_qa_log_message(
  p_test_run_id text,
  p_turn_no     integer,
  p_role        text,
  p_content     text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare v_id bigint;
begin
  if not app_is_admin() then
    raise exception 'AWN_FORBIDDEN: للإداريين فقط.';
  end if;
  if not exists (select 1 from qa_test_runs where test_run_id = p_test_run_id) then
    raise exception 'AWN_NOT_FOUND: اختبار مش موجود: %', p_test_run_id;
  end if;

  insert into qa_test_messages (test_run_id, turn_no, role, content)
  values (p_test_run_id, p_turn_no, p_role, coalesce(p_content, ''))
  returning id into v_id;

  return jsonb_build_object('id', v_id);
end;
$$;
grant execute on function public.admin_qa_log_message(text, integer, text, text) to authenticated;

create or replace function public.admin_qa_log_flag(
  p_test_run_id   text,
  p_turn_no       integer,
  p_message_id    bigint,
  p_raw_flag_text text,
  p_scenario      text default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare v_id text;
begin
  if not app_is_admin() then
    raise exception 'AWN_FORBIDDEN: للإداريين فقط.';
  end if;
  if not exists (select 1 from qa_test_runs where test_run_id = p_test_run_id) then
    raise exception 'AWN_NOT_FOUND: اختبار مش موجود: %', p_test_run_id;
  end if;

  v_id := 'FLAG-' || lpad(nextval('qa_flag_seq')::text, 4, '0');

  insert into qa_test_flags (flag_id, test_run_id, turn_no, message_id, raw_flag_text, scenario)
  values (v_id, p_test_run_id, p_turn_no, p_message_id, coalesce(p_raw_flag_text, ''), p_scenario);

  update qa_test_runs set total_flags = total_flags + 1 where test_run_id = p_test_run_id;

  return jsonb_build_object('flag_id', v_id);
end;
$$;
grant execute on function public.admin_qa_log_flag(text, integer, bigint, text, text) to authenticated;

-- ----------------------------------------------------------------------------
-- 4) قفل التشغيلة
-- ----------------------------------------------------------------------------
create or replace function public.admin_qa_finish_test_run(
  p_test_run_id text,
  p_status      text,
  p_total_turns integer default null,
  p_flag_counts jsonb default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
begin
  if not app_is_admin() then
    raise exception 'AWN_FORBIDDEN: للإداريين فقط.';
  end if;
  if p_status not in ('passed', 'failed', 'stopped', 'error') then
    raise exception 'AWN_BAD_INPUT: حالة مش معروفة: %', p_status;
  end if;

  update qa_test_runs
     set status         = p_status,
         ended_at       = now(),
         total_turns    = coalesce(p_total_turns, total_turns),
         critical_flags = coalesce((p_flag_counts ->> 'critical')::integer, critical_flags),
         major_flags    = coalesce((p_flag_counts ->> 'major')::integer, major_flags),
         minor_flags    = coalesce((p_flag_counts ->> 'minor')::integer, minor_flags)
   where test_run_id = p_test_run_id;

  if not found then
    raise exception 'AWN_NOT_FOUND: اختبار مش موجود: %', p_test_run_id;
  end if;

  return jsonb_build_object('test_run_id', p_test_run_id, 'status', p_status);
end;
$$;
grant execute on function public.admin_qa_finish_test_run(text, text, integer, jsonb) to authenticated;

-- ----------------------------------------------------------------------------
-- 5) ربط تنفيذات n8n الحقيقية بالرسايل — دليل مش تخمين
-- ----------------------------------------------------------------------------
-- خطوتين:
--  أ) وسم أي رسالة بوت فيها نص الفشل الثابت (Agent Error Fallback) كـ
--     is_agent_error — ده دليل مؤكد 100% (مطابقة نص حرفي)، مش استنتاج.
--  ب) ربط باقي رسايل البوت (الناجحة بس) بصفوف flow_execution_log الحقيقية
--     في نفس النافذة الزمنية للتشغيلة، بالترتيب — لأن Log Execution بيتسجل
--     فقط عند نجاح الـ AI Agent، فعدد صفوف اللوج المفروض يساوي عدد رسايل
--     البوت الناجحة بالظبط.
create or replace function public.admin_qa_correlate_executions(p_test_run_id text)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare
  v_run                 qa_test_runs%rowtype;
  v_session_id          text;
  v_updated             integer := 0;
  v_agent_error_marked  integer := 0;
begin
  if not app_is_admin() then
    raise exception 'AWN_FORBIDDEN: للإداريين فقط.';
  end if;

  select * into v_run from qa_test_runs where test_run_id = p_test_run_id;
  if not found then
    raise exception 'AWN_NOT_FOUND: اختبار مش موجود: %', p_test_run_id;
  end if;
  if v_run.test_chat_id is null then
    return jsonb_build_object('updated', 0, 'agent_errors_marked', 0, 'reason', 'no_chat_id');
  end if;

  v_session_id := v_run.test_chat_id || '-' || v_run.bot_key;

  update qa_test_messages
     set is_agent_error = true
   where test_run_id = p_test_run_id
     and role = 'bot'
     and content ilike '%something went wrong on my end%';
  get diagnostics v_agent_error_marked = row_count;

  with ordered_msgs as (
    select id, row_number() over (order by turn_no) as rn
      from qa_test_messages
     where test_run_id = p_test_run_id
       and role = 'bot'
       and is_agent_error = false
  ),
  ordered_logs as (
    select n8n_execution_id, n8n_workflow_id,
           row_number() over (order by occurred_at, id) as rn
      from flow_execution_log
     where session_id = v_session_id
       and occurred_at >= v_run.started_at
       and occurred_at <= coalesce(v_run.ended_at, now()) + interval '2 minutes'
  )
  update qa_test_messages m
     set n8n_execution_id = l.n8n_execution_id,
         n8n_workflow_id  = l.n8n_workflow_id
    from ordered_msgs om
    join ordered_logs l on l.rn = om.rn
   where m.id = om.id;
  get diagnostics v_updated = row_count;

  update qa_test_runs r
     set n8n_workflow_id = (
       select m.n8n_workflow_id from qa_test_messages m
        where m.test_run_id = r.test_run_id and m.n8n_workflow_id is not null
        limit 1
     )
   where r.test_run_id = p_test_run_id;

  return jsonb_build_object('updated', v_updated, 'agent_errors_marked', v_agent_error_marked);
end;
$$;
grant execute on function public.admin_qa_correlate_executions(text) to authenticated;

-- ----------------------------------------------------------------------------
-- 6) قراءة (قايمة التشغيلات + تفصيل تشغيلة واحدة كاملة)
-- ----------------------------------------------------------------------------
create or replace function public.admin_qa_list_test_runs(
  p_bot_key text default null,
  p_limit   integer default 50
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
begin
  if not app_is_admin() then
    raise exception 'AWN_FORBIDDEN: للإداريين فقط.';
  end if;

  return coalesce((
    select jsonb_agg(to_jsonb(t) order by t.started_at desc)
    from (
      select r.test_run_id, r.bot_key, r.status, r.started_at, r.ended_at,
             r.total_turns, r.total_flags, r.critical_flags, r.major_flags, r.minor_flags,
             r.parent_test_run_id, s.full_name as test_doctor_name
        from qa_test_runs r
        left join staff s on s.id = r.test_staff_id
       where p_bot_key is null or r.bot_key = p_bot_key
       order by r.started_at desc
       limit p_limit
    ) t
  ), '[]'::jsonb);
end;
$$;
grant execute on function public.admin_qa_list_test_runs(text, integer) to authenticated;

create or replace function public.admin_qa_get_test_run(p_test_run_id text)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare
  v_run jsonb;
begin
  if not app_is_admin() then
    raise exception 'AWN_FORBIDDEN: للإداريين فقط.';
  end if;

  select to_jsonb(r) || jsonb_build_object(
           'test_doctor_name', s.full_name,
           'workspace_name', w.name,
           'org_name', o.name
         )
    into v_run
    from qa_test_runs r
    left join staff s on s.id = r.test_staff_id
    left join workspaces w on w.id = r.workspace_id
    left join orgs o on o.id = w.org_id
   where r.test_run_id = p_test_run_id;

  if v_run is null then
    raise exception 'AWN_NOT_FOUND: اختبار مش موجود: %', p_test_run_id;
  end if;

  return v_run || jsonb_build_object(
    'messages', coalesce((
      select jsonb_agg(to_jsonb(m) order by m.turn_no, m.id)
        from qa_test_messages m where m.test_run_id = p_test_run_id
    ), '[]'::jsonb),
    'flags', coalesce((
      select jsonb_agg(
               to_jsonb(f) || jsonb_build_object(
                 'root_cause', (
                   select to_jsonb(rc) from qa_root_cause_analyses rc
                    where rc.flag_id = f.flag_id
                    order by rc.analyzed_at desc limit 1
                 )
               ) order by f.created_at
             )
        from qa_test_flags f where f.test_run_id = p_test_run_id
    ), '[]'::jsonb)
  );
end;
$$;
grant execute on function public.admin_qa_get_test_run(text) to authenticated;

-- ----------------------------------------------------------------------------
-- 7) حفظ نتيجة تحليل السبب الجذري (Root Cause Analyzer)
-- ----------------------------------------------------------------------------
create or replace function public.admin_qa_update_flag_analysis(
  p_flag_id           text,
  p_severity          text default null,
  p_category          text default null,
  p_scenario          text default null,
  p_expected_behavior text default null,
  p_actual_behavior   text default null,
  p_confidence        numeric default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare v_test_run_id text;
begin
  if not app_is_admin() then
    raise exception 'AWN_FORBIDDEN: للإداريين فقط.';
  end if;

  update qa_test_flags
     set severity          = coalesce(p_severity, severity),
         category          = coalesce(p_category, category),
         scenario          = coalesce(p_scenario, scenario),
         expected_behavior = coalesce(p_expected_behavior, expected_behavior),
         actual_behavior   = coalesce(p_actual_behavior, actual_behavior),
         confidence        = coalesce(p_confidence, confidence),
         status            = 'analyzed'
   where flag_id = p_flag_id
  returning test_run_id into v_test_run_id;

  if v_test_run_id is null then
    raise exception 'AWN_NOT_FOUND: ملاحظة مش موجودة: %', p_flag_id;
  end if;

  update qa_test_runs r
     set critical_flags = (select count(*) from qa_test_flags where test_run_id = v_test_run_id and severity = 'critical'),
         major_flags    = (select count(*) from qa_test_flags where test_run_id = v_test_run_id and severity = 'major'),
         minor_flags    = (select count(*) from qa_test_flags where test_run_id = v_test_run_id and severity = 'minor')
   where r.test_run_id = v_test_run_id;

  return jsonb_build_object('flag_id', p_flag_id);
end;
$$;
grant execute on function public.admin_qa_update_flag_analysis(text, text, text, text, text, text, numeric) to authenticated;

create or replace function public.admin_qa_save_root_cause(
  p_flag_id                   text,
  p_first_divergence_stage    text,
  p_first_divergence_node     text,
  p_root_cause_category       text,
  p_root_cause_explanation    text,
  p_evidence                  jsonb,
  p_downstream_impact         text,
  p_recommended_investigation text,
  p_recommended_fix           text,
  p_confidence                numeric,
  p_raw_llm_response           jsonb default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare v_id bigint;
begin
  if not app_is_admin() then
    raise exception 'AWN_FORBIDDEN: للإداريين فقط.';
  end if;
  if not exists (select 1 from qa_test_flags where flag_id = p_flag_id) then
    raise exception 'AWN_NOT_FOUND: ملاحظة مش موجودة: %', p_flag_id;
  end if;

  insert into qa_root_cause_analyses
    (flag_id, first_divergence_stage, first_divergence_node, root_cause_category,
     root_cause_explanation, evidence, downstream_impact, recommended_investigation,
     recommended_fix, confidence, raw_llm_response)
  values
    (p_flag_id, p_first_divergence_stage, p_first_divergence_node, p_root_cause_category,
     p_root_cause_explanation, p_evidence, p_downstream_impact, p_recommended_investigation,
     p_recommended_fix, p_confidence, p_raw_llm_response)
  returning id into v_id;

  return jsonb_build_object('id', v_id);
end;
$$;
grant execute on function public.admin_qa_save_root_cause(text, text, text, text, text, jsonb, text, text, text, numeric, jsonb) to authenticated;

-- ============================================================================
-- 8) إصلاح admin_conversations_feed — باج ترقيم قديم مستقل عن الميزة دي، بس
--    لازم يتصلح هنا لأن ربط التنفيذات الجديد بيعتمد على منطق سليم للتزامن.
--    منقول بالظبط من migrations/022_fix_conversation_execution_pairing.sql:
--    كان الترقيم بيتم من أول المحادثة (غلط لأي حالة أقدم من وقت بدء التسجيل)،
--    بقى بيترقّم من آخر رسالة للخلف (turn_from_end) على الجانبين.
-- ============================================================================
create or replace function public.admin_conversations_feed(
  p_staff_id uuid,
  p_bot_key  text default null,
  p_since    timestamptz default null,
  p_limit    integer default 200,
  p_offset   integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
begin
  if not app_is_admin() then
    raise exception 'AWN_FORBIDDEN: للإداريين فقط.';
  end if;

  return coalesce((
    select jsonb_agg(to_jsonb(page) order by page.msg_id desc)
    from (
      with channels as (
        select sc.bot_key, sc.external_id as chat_id,
               (sc.external_id || '-' || sc.bot_key) as session_id
          from staff_channels sc
         where sc.staff_id = p_staff_id
           and sc.is_active
           and (p_bot_key is null or sc.bot_key = p_bot_key)
      ),
      numbered as (
        select h.id as msg_id, c.bot_key, h.session_id, h.message,
               row_number() over (partition by h.session_id order by h.id) as seq,
               count(*) over (partition by h.session_id) as total_seq
          from n8n_chat_histories h
          join channels c on c.session_id = h.session_id
      ),
      turns as (
        select msg_id, bot_key, session_id, message,
               ((total_seq - seq) / 2) as turn_from_end,
               case when seq % 2 = 1 then 'human' else 'ai' end as fallback_role
          from numbered
      ),
      logs as (
        select l.session_id, l.n8n_workflow_id, l.n8n_execution_id, l.occurred_at,
               row_number() over (partition by l.session_id order by l.occurred_at desc, l.id desc) - 1
                 as turn_from_end
          from flow_execution_log l
          join channels c on c.session_id = l.session_id
      )
      select t.msg_id, t.bot_key,
             coalesce(t.message->>'type', t.message->'data'->>'type', t.fallback_role) as role,
             coalesce(t.message->>'content', t.message->'data'->>'content') as content,
             lg.n8n_workflow_id, lg.n8n_execution_id, lg.occurred_at
        from turns t
        left join logs lg on lg.session_id = t.session_id and lg.turn_from_end = t.turn_from_end
       where p_since is null or lg.occurred_at is null or lg.occurred_at >= p_since
       order by t.msg_id desc
       limit p_limit offset p_offset
    ) page
  ), '[]'::jsonb);
end;
$$;
grant execute on function public.admin_conversations_feed(uuid, text, timestamptz, integer, integer) to authenticated;
