-- ============================================================================
-- Migration 063: طلبات الباقات — تتبّع داخلي بسيط لصفحة "الاشتراكات والتحكم"
-- ============================================================================
-- مش نموذج عام للأطباء أو للعملاء — المدير نفسه بيسجّل "فيه عميل طلب باقة
-- جديدة" أو "فلان عايز يغيّر اشتراكه" عشان يفضل عنده سجل متابعة، وبعدين يقفلها
-- (approved/rejected) بعد ما ينفّذها فعليًا (تغيير الباقة نفسه بيتم من زرار
-- الباقة الموجود في subscriptions.html، مش من هنا — الطلب ده تسجيل نية بس).
-- ============================================================================

create table if not exists public.plan_requests (
  id                   bigint generated by default as identity primary key,
  workspace_id         uuid references public.workspaces(id),
  kind                 text not null check (kind = any (array['new_plan','subscription_change'])),
  requested_plan_name  text,
  details              text,
  status               text not null default 'pending'
                        check (status = any (array['pending','approved','rejected'])),
  created_at           timestamptz not null default now(),
  resolved_at          timestamptz
);

create index if not exists ix_plan_requests_status on public.plan_requests (status, created_at desc);

create or replace function public.admin_create_plan_request(
  p_workspace_id uuid,
  p_kind text,
  p_requested_plan_name text,
  p_details text
)
returns bigint
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
declare
  v_id bigint;
begin
  if not app_is_admin() then
    raise exception 'AWN_FORBIDDEN: للإداريين فقط.';
  end if;
  if p_kind not in ('new_plan', 'subscription_change') then
    raise exception 'AWN_BAD_INPUT: kind لازم new_plan أو subscription_change.';
  end if;

  insert into plan_requests (workspace_id, kind, requested_plan_name, details)
  values (p_workspace_id, p_kind, nullif(btrim(coalesce(p_requested_plan_name, '')), ''),
          nullif(btrim(coalesce(p_details, '')), ''))
  returning id into v_id;

  return v_id;
end;
$$;

grant execute on function public.admin_create_plan_request(uuid, text, text, text) to authenticated;

create or replace function public.admin_list_plan_requests()
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
begin
  if not app_is_admin() then
    raise exception 'AWN_FORBIDDEN: للإداريين فقط.';
  end if;

  return coalesce((
    select jsonb_agg(to_jsonb(t) order by t.created_at desc)
    from (
      select r.id, r.kind, r.requested_plan_name, r.details, r.status,
             r.created_at, r.resolved_at, r.workspace_id,
             w.name as workspace_name, o.name as org_name
        from plan_requests r
        left join workspaces w on w.id = r.workspace_id
        left join orgs o       on o.id = w.org_id
    ) t
  ), '[]'::jsonb);
end;
$$;

grant execute on function public.admin_list_plan_requests() to authenticated;

create or replace function public.admin_resolve_plan_request(p_request_id bigint, p_status text)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $$
begin
  if not app_is_admin() then
    raise exception 'AWN_FORBIDDEN: للإداريين فقط.';
  end if;
  if p_status not in ('approved', 'rejected') then
    raise exception 'AWN_BAD_INPUT: status لازم approved أو rejected.';
  end if;

  update plan_requests
     set status = p_status, resolved_at = now()
   where id = p_request_id;

  if not found then
    raise exception 'AWN_NOT_FOUND: الطلب مش موجود.';
  end if;

  return jsonb_build_object('ok', true);
end;
$$;

grant execute on function public.admin_resolve_plan_request(bigint, text) to authenticated;
